### ISSUE TITLE
Create Animal Base Class

### ISSUE THREAD

**Issue by marclevin** [marclevin/GroupProject-Eco#2]
### Please create a base class for Animal that can extend to multiple types of animals.
--------------
Remember this is _abstract._ This means it should be as generalized as possible.
Attributes such as:
- Weight
- Colour
- Carnivore/Herbivore/Omnivore (Maybe an Enum)
- Daily Food Intake
- ETC
--------------
These types of attributes should be included.
Think of some applicable methods such as calculating their daily food intake based on their weight and diet etc...

// EDIT: Please make sure you tag your class as **serializable**.

**Comment by jackalman1408** [comment]
ill handle this quick ... will try submit it before end of the day
